# docker compose -f docker-compose.yml -f docker-compose.dev.yml up -d --build
services:
  redis:
    container_name: redis
    image: redis:7
    expose:
      - "6379"
    volumes:
      - redis_data:/data

  app:
    volumes:
      - .:/usr/src/app
    build:
      context: .
      dockerfile: Dockerfile.dev

volumes:
  redis_data:
